### ISSUE TITLE
GE List

### ISSUE THREAD

**Issue by jeer65** [jeer65/MyTaks#11]
1. Check the Catalog is not associate to nothing
2. Outside to the screen -> it come back and refresh
3. The third columns should contain a filter
4. Product is missing the letter "T"
5. We have to order also on the Tree View Catalog View
6. The parameters is not viewing
7. Delete on the button
8. Choice Create NEW Failed
   a. Click Add new on the choiche
9. Parameters -Delete is not working
10. Is not showing any data on the Specify Params by Choices
    b. Miss spelling the "Paramas"
11. Label Add Field 
12. Edit on the Label is showing the "Input String is not in correct format"
13. Index and Length must refer to a location within the string
14. Style - Screen Name - Large Font and center the screen 
15. AutoApprove Styles document
16. Error on the Style when we edit the upload document, is not saving
17. Recipe associate (if select all choices don't select the top level- attibutes)

---
1. Direct access to the ProductModel\Catalog

**Comment by JorgeAguila** [comment]
Resueltos puntos 3,4,6
7, 8 y 9 necesito cargar la versión y ver que pasa, lo mismo para el orden de los choices en el tree de navegación

**Comment by JorgeAguila** [comment]
5, 7 y 9 resueltos el 8 tengo que cambiar la versión para volver a probar
