### ISSUE TITLE
GE List Second Revision

### ISSUE THREAD

**Issue by JorgeAguila** [jeer65/MyTaks#12]
Product Model
P3: Fix telerik data content, was showing integers rather than strings shown in table

Catalog
C1: System should check when entering that there are no conflicts, overlaps on attribute FP/LP entries
C2: Refresh treeview to reorder attributes when they have been edited
C3: Editing FP/LP with 5,5  then 5,6 then 5,5 throws an error
C4: Faster update.  During presentation it took 7 seconds to add a new attribute, should take 2-4 seconds
C5: Restrict Attribute name entry to length 50
C6: Removing underscores from selected recipe name

C8: Inactive check box should read "Active"
C9: Shrink columns to fit, or stack grids
C10:    Disable Delete button until the row is selected
C11:    Need to save Default Value to data model
C12:    Strip xxyy_ from 
C13:    Selecting all attributes from other catalogs with same prefix, rather than the appropriate selected attributes from only the selected catalog
C14: Add Available and Selected titles above the left and right selection grids
C15:    Add choice description into choice header
C16:    For Spec Values with long string, the comments are not coming in correctly always.  Check Magnum, Motor Operator, param Motor Operator
C17:    remove cancel buttons and use the tree view only to switch between options for Select Param Defs by
C18:    Cancel button   failed

C20:    Add column for Choice Description in Group By Param option
C21:    Change link name to "Specify, Group by Choice", "Specify, Group by Param"
C22:    Editing existing Catalog  adds a new "Click Add New" row in the Choice grid when Applying changes.

**Comment by JorgeAguila** [comment]
Resolved 01July2016
P3, 
C5, 7, 8, 10, 12, 16, 19

**Comment by jeer65** [comment]
P5- AND P16
Y ASEGURARTE QUE FUNCIONE IGUAL QUE COMO ANTES

**Comment by JorgeAguila** [comment]
P5 Solucionado, se terminaron los cambios de nuevo guardado de los catalog para acelerar su tiempo con éxito así como las pruebas correspondientes. se implemento.

C2 y C6 Atendidos 

Para Hoy C1, C22, C23 los dejo funcionando

**Comment by JorgeAguila** [comment]
Atendidos C2, C22, C1
En este Ultimo, programe una lista del tamaño del catalog seleccionado y recorri los attributos para verificar las posiciones ya guardadas, al momento de probarlo en el 104, salieron varias validaciones entre las que ya se resolvieron 
- La longitud del Catalog es Cero.
- Para el nuevo Attributo en la lista, lo marcábamos en el intervalo 1,1, con la nueva validación esto   ya no fúe posible ya que se siclaba como error, así que que programé la sugerencia de el posible valor mínimo a ocupar para sugerirlo como parte de la validación.
- Al continuar con las pruebas la validación anterior, falla añ momento de tener un catalogo cubierto en sus Attributos, ya que no encuentra sugerencia para mostrar ademas de el hecho de que ya se debe permitir dar de alta atributos en estos casos, 

Pendientes:
P16 Combo Telerik en rpoduct Model
Concluir la programación de la validación  de los catalog cuando ya tiene todos los atributos.
Con la validación Proficy muestra un mensaje de valor null que ya depure varias veces y no se muestra al correr paso a paso la deje pendiente para seguir checando

**Comment by jeer65** [comment]
07-06-16 REVISION
P16 -Telerik no esta mostrando los valores seleccionado en el "SELECTVALUE"
C23 - Create new cat # is not working, I get an error message
C24 - Cuando inicia desabilitar el Nombre hasta que selecciono alguno

**Comment by JorgeAguila** [comment]
C23 y C24 Cumplidas y cargadas en EATON  P16 pendiente
Con respecto a los Recipes R1, R3 y R10 Cumpletados
