### ISSUE TITLE
Recipe Association Page

### ISSUE THREAD

**Issue by jeer65** [jeer65/MyTaks#2]
1. No salen Catalogos en el Recipe
2. El boton de guardado habilitarlo cuando hay un cambio
3. El boton de cancel que funcione
4. Agregar los estilos en la pagina, copiar store procedure ?
5. Limpiar los comboboxes cada vez que el usuario selecciones un combobox sus dependientes deben de limpiarse

**Comment by JorgeAguila** [comment]
Los voy a atender el día de Hoy 10Jun2016 bajo el siguiente Orden 
Stylos (Punto 3)
Boton de Guardado (Punto 1)
Boton de Cancel Punto (2)

**Comment by JorgeAguila** [comment]
Stylos ya están agregados voy a probarlos nuevamente.
Boton de guardado encontre un error al momento de guardar los stylos voy a verificarlo hoy
Boton Cancel, no encuentro el problema, solicito apoyo.

**Comment by JorgeAguila** [comment]
La modificación de hoy, limpiaron los combos y no pude cambiar a la ultima ya se acabo el tiempo del tocken

**Comment by jeer65** [comment]
Falta la Navegacion hacia la Valicion

**Comment by JorgeAguila** [comment]
hoy queda
