### ISSUE TITLE
Validate Page

### ISSUE THREAD

**Issue by jeer65** [jeer65/MyTaks#3]
1. Add the information from the Recipe details
2. Show how many recipes are associated to the screen
3. Export Excel funcionality
4. Add the filter for the style
5. Layout doesn't fit correctly, please create a user friendly layout

**Comment by jeer65** [comment]
Hoy Jorge empieza a trabjar con el punto 1 y 5. 
Store procedure 30% -> HOY 6/23/15 se termina 
El Layout 40% -> HOY 6/23/15 Se entrega

**Comment by jeer65** [comment]
Retomar este trabajo para el 7-05-16

**Comment by JorgeAguila** [comment]
Retomo Esta parte Hoy
