### ISSUE TITLE
Product Model

### ISSUE THREAD

**Issue by jeer65** [jeer65/MyTaks#4]
1. When you click on Cancel button you have to refresh the page since you can assign the catalog value on other PM
2. En un nuevo PM el boton the active debe estar check per default
3. En nuevo Catalog me falla si no hay nada asignado
4. Cuando selecciono Edit me marca un error si no seleccionado seleccionar primero
   4.a Duplicar esto cuando doy Edit
5. New Attribute/Choice marca error cuando lo creas - solo en "ciertos" Catalogos
6. Ordenar los catalogos

**Comment by JorgeAguila** [comment]
1 Verificado y corregido, solicito confirmación
2. Verificado y corregido 
3. Verificado y corregido
4.Verificado y Corregido
5. No encontré el error en EATONDEV
6. En EATONDEV ya se muestran ordenados, lo único que se me ocurre es volver a pasar todo
