### ISSUE TITLE
Probar AdminDisplay de Forma Remota en EATON

### ISSUE THREAD

**Issue by JorgeAguila** [jeer65/MyTaks#5]
Instalar Profisy Client Remote
Conectarse y hacer pruebas de acceso

**Comment by JorgeAguila** [comment]
El Archivo que copie el día de ayer 12Jun2016, no se instala, me indica que necesita un proficy instalado, me imagino que solamente es el Service Pack.
Estoy reinstalando el CheckPoint EndPoint , solo que ya esta tardando bastante.

**Comment by jeer65** [comment]
This works by installing the same version client and Server
