### ISSUE TITLE
Modificar el esquema de seguridad a solo dos usuarios

### ISSUE THREAD

**Issue by JorgeAguila** [jeer65/MyTaks#6]
- Depurar el código para bloquear la seguridad actual.
- Modificar la seguridad para hacer solo dos Usuarios, uno general y una administrador
- al usuario Administrador habilitar botones (pendiente indicar cuales)

**Comment by JorgeAguila** [comment]
Voy a verificar lo de los Recipes y me Paso a éste punto Hoy 12Jun2016

**Comment by jeer65** [comment]
Is not able to login on the Admin display.
Please allow everyone to login on the pages add the reason why is not login
