### ISSUE TITLE
Navegacion

### ISSUE THREAD

**Issue by jeer65** [jeer65/MyTaks#8]
1.  Screens need headers b/c you cannot tell which “button” screen you are in displayed (TDMUnitTestArea_>Administrator Display->Manufacturing Lines)
2. On the Manufacturing line the Facility is showing data for area and should display data for Facility
3. Store procedure to get he Manufacturing Line has some issues, correct to show Lines

**Comment by JorgeAguila** [comment]
1. Treated and loaded
2. Treated and loaded
3. corrected

**Comment by jeer65** [comment]
Header -> 6/24/16 promise deliver

**Comment by jeer65** [comment]
CHECK WITH ABOUT THE LOGIN VALIDATION
